version: "3.1"
services:
    mysql:
        container_name: mysql
        image: hypriot/rpi-mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
            MYSQL_ROOT_PASSWORD: root
        restart: always
        volumes:
          - db:/var/lib/mysql
    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin:5.1.0        
        links:
            - mysql:db
        ports:
            - 8081:80
        environment:
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
            MYSQL_ROOT_PASSWORD: root
        restart: always
        volumes:
            - /sessions
volumes:
  db:
