version: "3.1"
services:
    mysql:
        container_name: mysql
        image: hypriot/rpi-mysql
        ports:
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: myDb
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./bancos:/docker-entrypoint-initdb.d
            - ./bancos/config:/etc/mysql/conf.d
            - persistent:/var/lib/mysql
        networks:
            - default
    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin/phpmyadmin:5.1.0
        links:
            - mysql:db
        ports:
            - 8081:80
        environment:
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
            MYSQL_ROOT_PASSWORD: root
volumes:
    persistent:
