version: '3.1'

services:

  mariadb:
    image: mariadb:latest
    container_name: my-mariadb
    restart: always
    environment:
      MARIADB_USER: admin
      MARIADB_PASSWORD: pass
      MARIADB_ROOT_PASSWORD: pass
    volumes:
      - "./mariadb-data/data:/var/lib/mysql/data/"
      - "./mariadb-data/logs:/var/lib/mysql/logs/"
    ports:
      - 3306:3306
     
  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 81:80
    environment:
      - PMA_ARBITRARY=1