version: "3.7"

services:   

   container1:
        build: .
        image: teste-ubuntu:14.04 
        container_name: container1
        image: teste-ubuntu:14.04
        networks: 
           ubuntu_rede:
             aliases: 
               - rede
        volumes:
               - ./pasta:/home/
        entrypoint: /bin/sh
        stdin_open: true
        tty: true

   container2:
        container_name: container2
        image: teste-ubuntu:14.04
        networks: 
           ubuntu_rede:
             aliases: 
               - rede
        volumes:
               - ./pasta:/home/
        entrypoint: /bin/sh
        stdin_open: true
        tty: true

networks:
   ubuntu_rede:
      name: rede
      driver: bridge
      ipam:
         driver: default