services:

  web:
    image: fabricioitajuba/apache-php-ssl:latest
    container_name: apache-php-https
    restart: always
    volumes:
      - ./conf:/etc/apache2/sites-available/
      - ./cert:/etc/ssl/certs/
      - ./cert:/etc/ssl/private/
      - ./www:/var/www/html/
    ports:
      - "443:443"
    networks:
      - default

